### ISSUE TITLE
Documentation for dandelifeon and petro petunia are not in the base Lexica, and have no usage documentation.

### ISSUE THREAD

**Issue by TeamDman** [KAfable/FTB-Interactions#205]
Submitter: `Interactions#0220`
Body: `**[Kezzar_Gassi]** OwO issue "Documentation for dandelifeon and petro petunia are not in the base Lexica, and have no usage documentation."`
Attachments:

**Comment by Saereth** [comment]
oh boy this looks like a pain in the ass to do -_-
https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/Botania/Lexicon/

if anyone else wants to try and tackle it and submit a PR that'd be nice otherwise I'll get to it... someday

**Comment by Vyraal1** [comment]
honestly, Im just gucci with a JEI tooltip. I never bothered to try Lexicon stuff because it feels like its too much work for the amount of payoff.
