### ISSUE TITLE
add an alternative quest route to philo stone requiring an emerald

### ISSUE THREAD

**Issue by TeamDman** [KAfable/FTB-Interactions#726]
Submitter: `FTB Interactions#2470`
Body: `**[coolprez]** OwO issue "add an alternative quest route to philo stone requiring an emerald"`
Attachments:

**Comment by Saereth** [comment]
should just add a note on the quest "After curing the villager, If you are feeling benevolent, the peace of patience may shed a new light on the secrets of the philsopher's stone."
