### ISSUE TITLE
The celestial altar quest has a prerequisite of stellar alloy dust, while the altar is crafted with sterling silver

### ISSUE THREAD

**Issue by TeamDman** [KAfable/FTB-Interactions#733]
Submitter: `Kel#1990`
Body: `OwO issue "The celestial altar quest has a prerequisite of stellar alloy dust, while the altar is crafted with sterling silver"`
Attachments:

**Comment by Saereth** [comment]
this is just a quest prerequisite issue can be fixed servers ide
